### ISSUE TITLE
8- Adaptation du tableau de bord bilan de compétences

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#11]
Adaptation du contenu des tableaux de bords par compétences pour avoir un rendu comme cela : 

![Image](https://user-images.githubusercontent.com/97050678/235623177-f2b39c6b-0aa2-46fc-8a3f-7c32db93470a.png)

**Comment by olivier-gerbe** [comment]
Ouh là là
gros travail, cat très différent de KAPC

**Comment by AdrienPrugnaud** [comment]
Isabelle s'occupe des dernières modifications en rapport avec le Genially

**Comment by AdrienPrugnaud** [comment]
Fait
