### ISSUE TITLE
11- Génération de PDF pour communication avec les tuteurs

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#13]
L’équipe Métier a indiqué qu’il était préférable (du fait que chaque tuteur n’aurait vraisemblablement qu’un seul participant) qu’une extraction des données en format pdf soit possible pour envoi par mail au tuteur.
Ceci pour simplifier le processus :
-	pas de nouveaux utilisateurs à créer,
-	pas de formation de prise en main de l’outil.
Les pages que le stagiaire pourrait obtenir en format pdf serait :
-	la fiche d’une situation professionnelle,
-	les bilans de La liste des actions par compétence,
-	le bilan de la formation,
-	le radar.
Voir fiche pdf d’exemples.

Les documents pdf à produire seront issus des pages du portfolio suivantes :
-	pages de situations professionnelles,
-	page du tableau de bord de mes actions par compétence,
-	page du tableau de bord du niveau atteint par compétence,
-	pages de mes bilans par compétence.
Des boutons Exporter en pdf ont été ajoutés sur les pages pour illustrer.

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/361a6570-4a33-492b-bccc-2cfcee3d90af)

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/a7ebe468-8711-4ab5-af55-6540edfa1c16)

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/91303d66-6858-4373-b483-6c429a7a1cbd)

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/ce41f171-de6c-4fac-8d90-c6685a3d118c)

**Comment by olivier-gerbe** [comment]
Impossible, il faut passer par l'impression pdf du browser
