### ISSUE TITLE
3- Données supplémentaires à ajoutés à l’instanciation

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#2]
Alimentation de données supplémentaires par l’intermédiaire des batchs à la création des portfolios des stagiaires reprises automatiquement dans la partie « Données personnelles » (civilité, prénom, nom, date de naissance, courriel, académie, fonction). 

Diapo "mon profil mon consentement", Données personnelles

**Comment by olivier-gerbe** [comment]
Fait
