### ISSUE TITLE
Bug affichage page de login avec Chrome

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#21]
Les modifications apportées par Olivier sur FF concernant la page de login ne sont pas reportées sur le navigateur Chrome (ex image de fond qui ne fait pas toute la page) : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/b1f15e0d-1744-4715-b623-150e76cdbda5)

**Comment by jgribonvald** [comment]
je n'ai plus le pb, mais je ne sais pas de quoi ça vient

**Comment by AdrienPrugnaud** [comment]
Je n'ai plus le souci
