### ISSUE TITLE
Menu : Mes Actions et Traces / Mes Actions / Mes Actions en Situation Professionnelle

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#28]
Dans ce menu, au moment du choix du niveau du positionnement, nous souhaitons afficher la description des niveaux afin de faciliter le choix de celui-ci.
Ecran actuel :

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/fff4de04-0fa2-42f9-9b61-4ce15b1e6ec7)

Type d’écran souhaité :

Exemple avec les différents choix à l’horizontal et les descriptions en dessous :

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/a54aad7b-a6ba-4406-9e38-ad67fe107cfa)

Exemple avec le même type d’écran qu’actuellement en ajoutant les descriptions à droite :

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/d647387d-e462-4480-ba40-83f23c23d439)

**Comment by AdrienPrugnaud** [comment]
Demande N° 2 d'IH2EF 
Seulement la deuxième solution de possible (avec un peu de CSS (on peut mettre du gras par exemple pour mettre en valeur des éléments) : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/aa5e98f5-cd75-4aec-908b-ed0107625ccc)

**Comment by AdrienPrugnaud** [comment]
Si on veut que les modifications soient appliquées dans les anciens portfolios il faudra passer un batch (et la réalisation du batch est plus compliquée aussi)

**Comment by FlorenceGrison** [comment]
Il faut aller chercher dans le référentiel, (mais les codes sont différents) / pas de relation" enfants" sur cette arborescence donc plus compliqué au final et pas de possibilité de rajouter des couleurs par ailleurs.

**Comment by AdrienPrugnaud** [comment]
Exemple de la deuxième solution au moment du rajoute de la compétence dans une SAP : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/aa30eab7-cdf7-4158-8500-0d8a1d6ccde3)

**Comment by FlorenceGrison** [comment]
Réunion avec IH2EF le 22/01: La solution proposée ne convient pas.  Ils veulent un un affichage descriptif de la description des niveau de positionnement, soit via une Info Bulle, soit via des jumelles qui pointeraient sur ce descriptif. 
Relance auprès d'ePortfolium pour trouver une autre alternative.

**Comment by FlorenceGrison** [comment]
![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/238c78e1-e3b0-481a-9c8d-bb60ee16365a)

**Comment by FlorenceGrison** [comment]
![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/ada6ce44-d854-4afa-8bd1-0b42daa44b67)

**Comment by FlorenceGrison** [comment]
![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/a26f55e9-357e-4e04-8f1d-44c8bac617d2)

**Comment by AdrienPrugnaud** [comment]
Pour l'instant on ne voit pas le descriptif : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/44fa536b-f40b-48ae-afb8-8cc375bac3e0)

A revalider avec Oliver car il avait été capable de faire ça : 


![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/82694388-753f-4b05-acc0-2ada0f43378b)

**Comment by FlorenceGrison** [comment]
Proposition d'Olivier le 20 juin:


![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/69093f9c-eb76-408a-a93d-f30ac9dc68e9)

**Comment by FlorenceGrison** [comment]
![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/d559632a-4a12-4561-97e8-8d099651cdfe)



![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/f007c5c3-5861-4ffb-836b-56e424abd278)

**Comment by FlorenceGrison** [comment]
**Information d'Olivier le 20 juin pour le front-end**


![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/ccce0153-3c5f-4660-8c59-6b9719264f11)
 **Réponse de Julien le 21 juin pour le front-end:**


![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/2bbc8517-7e1e-4e05-bd4f-fecdcb975ce2)

Réponse d'Olivier pour le front-end le 22/06



![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/b5f42d40-be81-43cd-87a4-48ca607eccd9)

**Comment by FlorenceGrison** [comment]
Julien doit mettre à jour le frontend  prochainement,ce qui nous permettra de confirmer les modifications faites par Olivier. et s'assurer que pas d’autres bugs réapparus.  Si tout est OK; on pourra partager des portfolios de tests à Delphine et Aurélie . Quand elles auront validé que c'est OK , il restera les batchs de mise à jour à passer des portfolios existant.

**Comment by AdrienPrugnaud** [comment]
Fait : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/a716a6a8-31c3-4ba9-89cd-9f778e254789)

Il faudra qu'ePortfolium l'applique sur l'ensemble des formations

**Comment by FlorenceGrison** [comment]
18 juillet - 
- Tous les espaces entre les lignes dans les  niveaux atteints sont désormais identique.
- L'intitulé du niveau atteint dans le bandeau de couleur est un peu décalé pour une meilleure lecture
- Un curseur rouge en début de bandeau indique désormais ou l'étudiant se positionne , ce qui facilite la sélection du niveau atteint  

![Image](https://github.com/user-attachments/assets/91b23c67-5b91-408d-a7bb-6fb7441c82ad)

**Comment by AdrienPrugnaud** [comment]
Fonctionne correctement : 

![Image](https://github.com/user-attachments/assets/1f071098-2405-4cdd-9d16-024370a25417)
