### ISSUE TITLE
4- Modifications des batchs de créations des étudiants automatiques et des batchs d’alimentation

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#3]
Modification des batchs de création des stagiaires avec les données supplémentaires de l'issue "Données supplémentaires à ajoutés à l’instanciation" et des batchs de création automatique « Batch changer formation étudiants »… en rajoutant ces informations

**Comment by olivier-gerbe** [comment]
Fait

**Comment by AdrienPrugnaud** [comment]
Voir avec Isabelle pour les batchs des 3 modèles (1D, 2D, et responsable) car Olivier n'aura pas le temps
