### ISSUE TITLE
Menu : Mes bilans par compétence / Ecran de la compétence

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#30]
Dans ce menu, nous souhaitons permettre aux utilisateurs de créer plusieurs analyses à des moments différents sans avoir à supprimer ce qu’ils avaient écrit avant afin de conserver leur historique personnel.

Cela impliquerait de pouvoir avoir plusieurs blocs de questions, chacun avec une date. La date se met automatiquement à la date de création de la nouvelle analyse.

Il faudrait ajouter un bouton « Nouvelle analyse », à chaque clic sur ce bouton, on intègre un nouveau bloc d’analyse avec les deux lignes actuelles.

On met la date du jour sur l’analyse et on ajoute un icône « Poubelle » pour permettre la suppression d’une analyse si besoin.

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/8da82332-7d6f-498d-9697-6b960d99d1d0)

**Comment by AdrienPrugnaud** [comment]
Demande N° 3 d'IH2EF 
Pas compliqué, c'est juste un élément à rajouter dans les 3 modèles

**Comment by AdrienPrugnaud** [comment]
Si on doit changer dans les portfolios anciens il faudra un batch

**Comment by FlorenceGrison** [comment]
Nécessité d'un batch sur les 1200 portfolios existants (déjà déployés) et donc les 3 modèles de formations.  Il faut communiquer à OIivier Gerbé 5 ou 6 portfolios très "fournis" pour faire un test sur ces quelques portfolios en exemple. 
Demander à Aurélie de nous faire suivre des portfolios d'étudiants existants.

**Comment by AdrienPrugnaud** [comment]
Modification effectué : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/54cff82b-1c31-44a4-86cf-3bfdf957f8b0)

Par contre le batch ne corrige pas les analyses passées

**Comment by FlorenceGrison** [comment]
Modèle de portfolios créé par Adrien pour qu'ePortfolium fasse les tests. Nom : "ePortfolio de stagiaire exemple 1 PERSONNEL DE DIRECTION".
**19/01** = ih2ef/1stagiaires.batch-maj-portfolios  ( Batch exécuté par ePortfolium) mais ne corrige pas les analyses antérieures. 
**Réunion IH2EF le 22/01** : confirme que souhaite que ce soit datée dès le début.  Envisage t'on la modification que sur les nouveaux portfolios Ou alors batch de correction pour pouvoir rajouter la date aussi pour les anciens car :
Est-ce qu'il est possible de voir avec Julien si cela posera problème pour les extractions de données si on n'aligne pas le fonctionnement des nouveaux et des anciens portfolio. Je pense aux dates dans l'analyse réflexive.

**Comment by AdrienPrugnaud** [comment]
Fait : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/21127ce6-dce1-4e48-9f9e-c952985dd45b)
