### ISSUE TITLE
Menu : Les compétences / Mon référentiel de formation / NOM DU REFERENTIEL

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#31]
Dans ce menu, il est souhaité modifier l’affichage des référentiels afin de mettre en colonne les étapes de développement de la compétence, et dessous, les libellés expliquant le contenu de cette étape de développement.

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/bb252f9b-d224-4b06-84ed-4f54bf928e85)

**Comment by AdrienPrugnaud** [comment]
CSS à modifier mais plus compliqué. Isabelle pourra prendre le relais pour rendre "beau" après la sortie de la 1.4 en février

**Comment by FlorenceGrison** [comment]
Demande N°4 d'IH2EF 
:  c'est un proxy donc tt le monde voit les modifications immédiatement en instantannée. Oui on peut obtenir les colonnes avec les couleurs comme demandées par IH2EF. . 
Il faut rajouter les 2 pictogrammes au niveau des critères  . Demander à Julien Gribonvald de les ajouter dans l'espace Karuta en format ping - png.

**Comment by AdrienPrugnaud** [comment]
Exemple de mise en forme (en cours) : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/61a45cd3-21cb-4c6f-a406-7fe71cfc3fbd)

A confirmer par Olivier s'il a terminé

**Comment by FlorenceGrison** [comment]
Réunion avec IH2EF le 22/01 : La proposition avec les colonnes et les repères avec les couleurs sont TB. Il faut garder le titre en dur et le texte en Live ET enlever le +- .  = Validé pour IH2EF 
Les pictos sont moins urgents et si économie à faire , IH2EF est ok pour enlever les pictos.

**Comment by AdrienPrugnaud** [comment]
Fait le titre est en dur, par contre il faudra revoir **l'alignement, les couleurs des titres, et la taille de la police ?** (car la dernière colonne n'a pas de couleur) : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/bddce683-14bc-4da6-814c-e14b515554a0)

**Comment by AdrienPrugnaud** [comment]
Ce qu'il reste à faire : 
- mettre en dure le titre (en enlever le fait pouvoir déplier/replier) comme sur les 1- et 2-
- changer les couleurs
- mettre une police un peu plus grande pour le contenu de la trajectoire (la taille des titres est bien)

Voilà ce que cela pourrait donner : 
![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/f98be67b-1831-4e5e-9eff-55f6bdd9babf)

- en bonus (si cela ne prend pas de temps) aimerait avoir un titre sur une seule ligne

**Comment by FlorenceGrison** [comment]
![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/40a33dd1-cad9-4ca8-b64a-41404749d2ce)

**Comment by FlorenceGrison** [comment]
![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/0a7996b4-89ec-4fa0-aa77-8c9727f8860c)

**Comment by FlorenceGrison** [comment]
**Information d'Olivier sur le front-end le 20/06**



![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/7df9138f-96ec-4ef8-b576-171c1190263b)


**Réponse Julien sur le front-end le 21/06**


![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/59c475d8-1527-4fa4-ad15-9de1ea63a26c)

**Réponse Olivier sur le front end le 22/06**


![Image](https://github.com/GIP-RECIA/IH2EF/assets/136322426/3606cda9-3e5f-41d8-b742-6b075363b81f)

**Comment by FlorenceGrison** [comment]
Julien doit mettre à jour le frontend  prochainement,ce qui nous permettra de confirmer les modifications faites par Olivier. et s'assurer que pas d’autres bugs réapparus.  Si tout est OK; on pourra partager des portfolios de tests à Delphine et Aurélie . Quand elles auront validé que c'est OK , il restera les batchs de mise à jour à passer des portfolios existant.

**Comment by AdrienPrugnaud** [comment]
Fait : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/f75b081b-d119-4307-847b-ef5ba9c51578)

Il faudra l'appliquer à l'ensemble des compétences et des référentiels

**Comment by AdrienPrugnaud** [comment]
Fait, à valider par l'IH2EF
