### ISSUE TITLE
Date du jour rajoutée automatiquement pour le niveau atteint sur la compétence (Demande N°1 ds Expression du Besoin)

### ISSUE THREAD

**Issue by FlorenceGrison** [GIP-RECIA/IH2EF#35]
Menu : Mes Actions et Traces / Mes Actions / Mes Actions en Situation Professionnelle
Dans ce menu, il arrive que l’utilisateur oublie de saisir une date. La situation professionnelle ne se retrouve donc pas sur l’écran du bilan par compétence.
Nous souhaitons qu’à la sélection du niveau atteint sur la compétence, la date du jour de la saisie se mette par défaut. L’utilisateur conservera la possibilité de modifier la date s’il le souhaite.

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/f01fd16b-3476-41f2-9019-e526fa369aae)

**Comment by FlorenceGrison** [comment]
Demande N° 1 d'IH2EF 
Fait mais à appliquer à tous les éléments (en cours)
Il n' y a pas de développement spécifique à faire. C'est une métadonnée à modifier.

**Comment by FlorenceGrison** [comment]
lkjglkjdfmjdsogiuezopru ttest

**Comment by AdrienPrugnaud** [comment]
Modification effectuée

**Comment by FlorenceGrison** [comment]
Réunion le 22/01 avec IH2EF: Lors de la sélection du niveau atteint sur la compétence, la date du jour se rajoutera automatiquement.  Le batch viendrait modifier les 1200 portfolios .Idéalement, il faut que l'ensemble des portfolios (anciens) et futurs bénéficient de cette modification.  Donc plus cher pour le batch.  mais conviendrai à IH2EF . On attend leur confirmation   pour le choix retenu.

**Comment by AdrienPrugnaud** [comment]
Fait : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/4936caae-b40b-4feb-bf51-41eb51e31323)

**Comment by AdrienPrugnaud** [comment]
Fait à valider par l'IH2EF
