### ISSUE TITLE
1- Configurer un ajout de compétences par bloc

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#4]
Le bouton d’ajout d’une compétence rajoute automatiquement l’ensemble des informations relatives à la compétence : ses « Critères d’exigence attendus dans la mise en œuvre de la compétence », les « Situations professionnelles de référence » et les « Trajectoire de développement de la compétence ».  Si possible avec un système pour cocher et choisir toutes les compétences d'un coup.
Attention il y aura une modification de la structure des référentiels car au niveau des trajectoires il n'y aura un descriptif désormais comme ce qui suit (et non plus une liste de tirets ) : 

![Image](https://user-images.githubusercontent.com/97050678/235673720-d960fee5-b0c0-40c8-ada4-fbb189fe413e.png)

**Comment by olivier-gerbe** [comment]
Fait

**Comment by AdrienPrugnaud** [comment]
Est-il possible pour chaque compétence, il y aura un bouton « + » qui permettra d’ouvrir et de consulter le détail de cette compétence : 
-	Les critères d’exigence,
-	Les situations professionnelles de références
-	La trajectoire de développement de la compétence

**Comment by olivier-gerbe** [comment]
Je ne comprends pas. Il y a un +/-

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe Je le vois correctement désormais, par contre comment faire pour rajouter "Les critères d’exigence", "Les situations professionnelles de références", "La trajectoire de développement de la compétence" etc... ? avec une présentation de se type : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/f2e3f36e-82ba-4b43-97f0-6dfc77a4d1b0)

**Comment by olivier-gerbe** [comment]
J'ai mis un proxy dans le référentiel import

**Comment by AdrienPrugnaud** [comment]
Merci Olivier, je suis preneur pour un guide/démo pour l'utilisation du proxy (rajouter des éléments etc...). Si possible il aimerait avoir un picto comme sur la pj ci-dessus à côté les critères d'exigence, des situations pro et des trajectoire de développement
