### ISSUE TITLE
6- Lien direct d'une page vers la page trace

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#7]
Mettre un lien vers la page trace grâce à un bouton cliquable comme ici : 
![Bouton cliquable](https://user-images.githubusercontent.com/97050678/234796143-e1ad6202-3ac8-404f-8f82-cf71dcc67677.png)

**Comment by olivier-gerbe** [comment]
Fait

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe petit rajout je n'arrive pas à me rediriger vers la page trace

**Comment by olivier-gerbe** [comment]
Oups! J'avais oublié de changer le menu du modèle page-action-stage
Fait

**Comment by AdrienPrugnaud** [comment]
Merci Olivier, je t'ai répondu dans les issues pour certains points 2- Tableau de bord de mes actions par compétence et 1- Configurer un ajout de compétences par bloc#4

Adrien

Le Mercredi 31 Mai 2023 19:34 CEST, Olivier Gerbé ***@***.***> a écrit:
 
 
Oups! J'avais oublié de changer le menu du modèle page-action-stage
Fait
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>


--

 Adrien PRUGNAUD / Chargé de mission ePortfolio
Port. +33 (0)6 49 17 61 ***@***.***

GIP Recia · Ressources numériques publiques en Centre-Val de Loire
Antenne de Touraine · 4-6, boulevard de Chinon · 37510 BALLAN-MIRÉ
Tél. 02 38 42 79 60
www.recia.fr ·
