### ISSUE TITLE
2- Tableau de bord de mes actions par compétence

### ISSUE THREAD

**Issue by AdrienPrugnaud** [GIP-RECIA/IH2EF#8]
Réalisation d’un tableau de bord comprenant ces éléments : 
"Sur la première colonne, on retrouve la liste des compétences listées dans la rubrique « les compétences ».
Sur la seconde colonne, on retrouve, face à chaque compétence, la trajectoire de développement de celle-ci.
Sous chaque compétence, on fait apparaître le libellé « Mes situations », et sous chaque étape de développement de la trajectoire, on fait apparaître un lien sous forme de puce sur chaque situation professionnelle (et SAé lorsqu’il y en aura).
Les liens seront cliquables pour permettre l’affichage de la page de la situation et en passant la souris sur la puce (ou autre pictogramme), on voit le nom de la situation."
Il faut aussi que les dates d'ajouts des compétences soit suivies dans le tableau

Le rendu attendu se trouve sur le genially dans la partie "Mes bilans par compétences" puis "Tableau de bord de mes actions par  compétence" : https://view.genial.ly/6358d494d02e0600194f5076

**Comment by olivier-gerbe** [comment]
Fait

**Comment by AdrienPrugnaud** [comment]
Concernant les points bleus quand je clique dessus rien ne se passe (on ne me renvoie pas vers la situation) : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/bacb4500-4420-4977-8954-71e575ab6931)

**Comment by olivier-gerbe** [comment]
Fait

**Comment by AdrienPrugnaud** [comment]
Merci, l'IH2EF souhaiterait aussi pouvoir regarder les référentiels de trajectoire et de compétences avec les boutons "?" (si ce n'est pas un "?" peut-être avec les jumelles ?) : 

![Image](https://github.com/GIP-RECIA/IH2EF/assets/97050678/8d2a2ce9-0cc3-4129-91b7-3a1ebefdbf82)

**Comment by AdrienPrugnaud** [comment]
En attente du nouveau découpage du tableau par l'IH2EF : changer la barre T1 T2 T3 et T4 à la place des noms de mois et (T1 = mois sept, oct, nov, T2 = dec, janv, fév, T3 = mars, avril mai, T4 = juin, juillet, août) => revoir découpage des mois avec Aurélie + ajout d'une légende en passant sur les T*

**Comment by AdrienPrugnaud** [comment]
Il reste le point de l'évolution du tableau de bord pour permettre au stagiaire de le conserver 4 ans.

**Comment by AdrienPrugnaud** [comment]
1- Corriger l'affichage des points noirs dans le tableau de bord qui ne s'affichent pas au bon endroit.

2-  Découpage final des dates servant de colonnes sur le tableau avec des trimestres (T1...) à la place des mois  :
T1 : Juillet-octobre
T2 : Novembre-Février
T3 : Mars-juin
(visuel du rendu diapo 15 : https://view.genial.ly/6358d494d02e0600194f5076/interactive-content-eportfolioscenariostagiaire1)

3- L'IH2EF souhaiterait ce tableau de bilan de compétences année par année sur une période de 4 ans. Les périodes de début/fin des années "scolaire" (de stage) sont visibles sur la slide 15 et le visuel du bouton souhaité (si possible) pour changer d'année et aussi sur la slide 15.

**Comment by AdrienPrugnaud** [comment]
+ couleurs finales du tableau de bord en attente de décision par l'IH2EF (ils sont mis des couleurs mais elles peuvent encore changées

**Comment by AdrienPrugnaud** [comment]
Concernant le tableau de bord l'IH2EF souhaiterait aussi avec une légende quand ils passent sur les T*. T1 : Juillet à octobre, T2 : Novembre à février, T3 : Mars à juin.

**Comment by AdrienPrugnaud** [comment]
Il ne reste plus que les couleurs à personnaliser

**Comment by AdrienPrugnaud** [comment]
Fait
